# Generated by Django 3.0 on 2021-02-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testinput', models.CharField(max_length=255, verbose_name='input smth')),
            ],
        ),
    ]
