# Generated by Django 3.0 on 2021-02-03 15:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testt', '0002_auto_20210203_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='InputModel',
        ),
    ]
