# Generated by Django 3.0 on 2021-02-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testt', '0003_auto_20210203_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testmodel',
            new_name='InputModel',
        ),
    ]
