# Generated by Django 3.0 on 2021-02-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testt', '0004_auto_20210203_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputModel',
            new_name='Testmodel',
        ),
    ]
